
# this line is important, do not change it! (project_id)
project_id = "whnwzoxwuipgmwkqcops"

[api]
# Port to use for the API URL.
port = 54321
# Schemas to expose in your API. Tables, views and stored procedures in this schema will get API
# endpoints. public and storage are always included.
schemas = ["public", "storage", "graphql_public"]
# Extra schemas to add to the search_path of every request. public is always included.
extra_search_path = ["public", "extensions"]
# Max rows returns in a single response. Applies to all API endpoints except GraphQL.
max_rows = 1000