// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = "https://whnwzoxwuipgmwkqcops.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indobnd6b3h3dWlwZ213a3Fjb3BzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyNTAxMzYsImV4cCI6MjA2MDgyNjEzNn0.SotkzJdh8sGT-fYK1vn01DtvfspEJmLF_bh5DEUz-UU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY
);
